# Generated by Django 5.1.7 on 2025-03-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semlor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('picture_name', models.CharField(max_length=200)),
                ('vegan', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('kind', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('semla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semlerating.semlor')),
            ],
        ),
    ]
