# Generated by Django 5.1.7 on 2025-03-27 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semlerating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='semla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='semlerating.semlor'),
        ),
    ]
