# Generated by Django 5.1.7 on 2025-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semlerating', '0002_alter_rating_semla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semlor',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
